name: PHP Coding Standards

on:
  push:
    branches:
      - trunk
      - develop
    paths:
      - "**.php"
      - .github/workflows/php-coding-standards.yml
  pull_request:
    paths:
      - "**.php"
      - .github/workflows/php-coding-standards.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: PHP coding standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare PHP
        uses: woocommerce/grow/prepare-php@actions-v1
        with:
          tools: cs2pr

      - name: Log PHPCS information
        run: vendor/bin/phpcs -i

      - name: Run PHPCS on all files
        run: vendor/bin/phpcs -q -n --report=checkstyle | cs2pr

      - name: Run PHPCS with PHP 5.2 on plugin loader file
        run: vendor/bin/phpcs facebook-for-woocommerce.php --runtime-set testVersion 5.2 -q -n --report=checkstyle
